version: '3'
services:
    ilias:
        image: sturai/ilias
        ports:
          - 8080:80
        links:
          - mysql
        environment:
          - ILIAS_AUTO_SETUP=1
          - ILIAS_DB_USER=root
          - ILIAS_DB_PASSWORD=example
          - ILIAS_ROOT_PASSWORD=homer
    mysql:
        image: mysql:5.7
        command: |
            --character-set-server=utf8
            --collation-server=utf8_general_ci
        environment:
          - MYSQL_ROOT_PASSWORD=example
          - MYSQL_DATABASE=ilias
