#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
runcmd:
  - logger "runcmd started"
  - logger "installing docker compose"
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  - sed -i 's/\r$//' /run.sh
  - touch /running
  - bash /run.sh
  - mv /running /finished
  - logger "runcmd finished"

write_files:
  - encoding: b64
    content: "${RUN_SH}"
    owner: root:root
    path: /run.sh
    permissions: '0644'
  - encoding: b64
    content: "${DOCKER_COMPOSE_YML}"
    owner: root:root
    path: ${REPOSITORY_PATH}/docker-compose.yml
    permissions: '0644'
