#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
runcmd:
  - logger "runcmd started"
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker run -d -p 80:80 hskatgl/lai
  - logger "runcmd finished"
