#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
runcmd:
  - logger "runcmd started"
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  #TODO add compose file (stack.yml): https://hub.docker.com/r/sturai/ilias/
  - logger "runcmd finished"
